### ISSUE TITLE
只有设置isMod才会被分析

### ISSUE THREAD

**Issue by PetersonLian** [fex-team/fis3-hook-cmd#12]
> 只有标记是模块化的 js 才会去解析。

readme里头如上所说。
我回头看了fis文档，文档里对于isMod的描述是：

> 说明：标记文件为组件化文件。被标记成组件化的文件会入map.json表。并且会对js文件进行组件化包装。

那么请问，如果我没理解错的话。`fis3-hook-commonjs`, `fis3-hook-amd`，这两个插件，也是只会去分析设置了isMod的文件。
是否如此？

**Comment by 2betop** [comment]
> 只有标记是模块化的 js 才会去解析。

这个解析是指语法解析。比如分析 define 语句， require 语句 （在 define 内、外是有不同的语意）。因为消耗比较大，所以只有 isMod 才会去处理。

但是正则分析还是会进行。毕竟不包裹的 js 也可能会 require 模块。

**Comment by PetersonLian** [comment]
计划将模块代码，都按照commonjs的风格编写。
如果需要amd风格，貌似fis的mod.js已支持的样子。所以，我暂时认为commonjs风格代码转化为amd风格是没有问题的。
我的问题在于，commonjs转cmd风格的代码。没用过seajs，目前个人想法是，以后真需要转cmd风格代码，到时候写个fis插件。
但，就怕，seajs没我想的简单（毕竟没用过seajs），可能存在大坑。

# 为什么我要使用commonjs，而不根据我相应的情况，确定成amd或者cmd（我目前只考虑浏览器端）？

我的想法是，目前我的新公司使用seajs。但是，如果下一家公司使用requirejs呢？当我无法改变加载器方案的情况下，我的想法是，我按照commonjs风格写的代码，使用特定插件，自动转化成amd或者cmd，这样我就不需要重写了。
求大神帮忙把控下。

# 问：commonjs代码转cmd代码，应该没有大坑吧？

**Comment by 2betop** [comment]
可以转，但是 sea.js 实在不知道为何要用，部分打包都不支持。

**Comment by PetersonLian** [comment]
好。我的希望就是commonjs的代码，然后release出来amd或cmd的代码。
只是这个插件目前不知道怎么写。
有seajs大神看到了，请赶快操刀。必须膜拜。
让我们P民抄抄。
