### ISSUE TITLE
对已经包裹了define的模块，fis3-hook-cmd 去掉了“module”关键字

### ISSUE THREAD

**Issue by dnstfly** [fex-team/fis3-hook-cmd#3]
未部署之前文件内容:define("arale-base/1.2.0/src/base-debug", ["arale-class/1.2.0/class-debug","arale-events/1.2.0/events-debug"], function(require, exports, module){}

使用插件后：
define("arale-base/1.2.0/src/base-debug", ["arale-class/1.2.0/class-debug", "arale-events/1.2.0/events-debug", "arale-class/1.2.0/class-debug", "arale-events/1.2.0/events-debug", "arale-base/1.2.0/src/aspect-debug", "arale-base/1.2.0/src/attribute-debug"], function(require, exports){}

去掉了module关键字

**Comment by snadn** [comment]
遇到了同样的问题，看源码，应该是解析define时按amd的规范解析导致的错误。求解决啊！

**Comment by 2betop** [comment]
https://github.com/fex-team/fis3-hook-cmd/releases/tag/0.1.2
