### ISSUE TITLE
模块化的 hook 不会自动添加依赖关系吗？

### ISSUE THREAD

**Issue by berryliu** [fex-team/fis3-hook-cmd#5]
你好，RT：
该插件使用中发现，尽管解析了 define 中的 deps 路径，但是并没有将该依赖关系加入到 RESOURCE_MAP 里。amd 的 hook 应该也类似，为什么？只是单纯的资源定位解析吗？

**Comment by 2betop** [comment]
只有异步依赖才会加进去，同步的页面里面就应该输出 script 引入了。注意是否启用了 loader 插件，如果你那没有引入的话。

**Comment by berryliu** [comment]
不太明白。我理解的是，同步依赖也是 fis 分析的，需要添加依赖关系。然后在 packager 的阶段统一分析 RESOURCE_MAP 输出成 script 给页面。
没有使用 loader，感觉太粗暴需要订制资源加载。

**Comment by berryliu** [comment]
还有就是，hook 是在哪个阶段对文件进行干预的？

**Comment by 2betop** [comment]
hook 是绑定事件进行干预，各种阶段都有可能。

loader 中会把同步的依赖直接生成 `script` 插入到页面，只有异步依赖才会生成 Resource map 插入页面。

**Comment by berryliu** [comment]
好的，那我看看 loader 中是如何实现的吧。谢谢！
